[virustotal]
api_key = "VIRUSTOTAL API KEY HERE"
scan_sleep = 15
scan_interval_seconds = 5

[moderation]
max_violations = 3
violation_window_minutes = 2
log_channel_id = CHANNEL ID FOR LOGGING
track_channel_id = CHANNEL ID FOR TRACKING
threshold = 2
verified_role_name = "Verified" 
member_role_name = "Member"
moderator_role_id = ROLE ID FOR MODS
tracked_notification_cooldown_seconds = 3600

[bot]
discord_token = "BOT DISCORD TOKEN HERE"
responsible_moderator_id = USER ID FOR RESPONSIBLE MODERATOR
silly_mode = false
debug_mode = false
scannable_file_extensions = [
    ".exe",
    ".dll",
    ".bin",
    ".dat",
    ".scr",
    ".zip",
    ".rar",
    ".tar.gz",
    ".py",
]
max_file_scan_size_mb = 30
presence = "Bot online."

[structure]
allowlist_path = "allowlist.json"
denylist_path = "denylist.json"
shortener_list_path = "shortener.json"
tracked_users_path = "tracked_users.json"
logging_dir = "logs"
max_log_lines = 5000
violation_path = "violations.json"
stats_path = "stats.json"
fuckup_path = "fuckups.json"
react_stats = "reactions.json"